Advisor/urls.py
from django.urls import path
from . import views
from .views import *
app_name = 'Advisor'
urlpatterns = [
    path('dashboard/', advisor_dashboard, name='advisor_dashboard'),
    path('manage-times/', manage_available_times, name='manage_available_times'),
    path('book-appointment/<int:advisor_id>/', book_appointment, name='book_appointment'),
    path('list-advisors/', list_advisors, name='list_advisors'),
    path('send-message/<int:appointment_id>/', send_message_view, name='send_message'),
    path('chat/<int:appointment_id>/', chat_page, name='chat_page'),
    path('chat_user/<int:appointment_id>/', user_chat_page, name='user_chat_page'),
]

main_page/urls.py
from django.urls import path
from . import views
from .views import *
app_name = 'main_page'
urlpatterns = [


    path('',views.post_list, name='list'),
    path('<int:slug>',views.post_detail, name='detail'),
    path('about/',views.about,name='about'),
    path('rate_comment/<int:comment_id>/', rate_comment, name='rate_comment'),

]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('Accounts.urls',namespace='accounts')),
    path('', include('main_page.urls',namespace='mainpage')),
    path('dashboard/', include('dash_board.urls',namespace='dashboard')),
    path('advisor/', include('Advisor.urls',namespace='advisor')),
    
    
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.ALLOWED_HOSTS:
   
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main_page/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from django.utils.text import slugify

class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(blank=True,null=True)
    
    
    def save(self, *args, **kwargs):
        super(Post, self).save(*args, **kwargs)  # Save the post first to get a valid pk
        if not self.slug:  # Check if the slug is empty
            self.slug = slugify(self.pk)
            super(Post, self).save(*args, **kwargs) 
        
        
    def __str__(self) :
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    def ratings_average(self):
        ratings = self.ratings.all()
        if ratings:
            average = sum(r.rating for r in ratings) / ratings.count()
            return round(average, 1)
        return 0


    def __str__(self):
        return self.text[:20] 
    
    
class CommentRating(models.Model):
    RATING_CHOICES = (
        (1, 'Very Poor'),
        (2, 'Poor'),
        (3, 'Average'),
        (4, 'Good'),
        (5, 'Excellent'),
    )
    comment = models.ForeignKey(Comment, related_name='ratings', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(choices=RATING_CHOICES)

    def __str__(self):
        return f"{self.user.username} rated {self.rating}/5"
    
    

main_page/forms.py
from django import forms
from .models import Post,Comment

class post_form(forms.ModelForm):
    class Meta:
      model = Post
      fields = ['title','content']
      
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

main_page/views.py
from django.http import HttpResponseForbidden
from django.urls import reverse
from django.shortcuts import render,redirect
from .models import Post,Comment,CommentRating
from django.core.paginator import Paginator
from .forms import post_form
from django.contrib.auth.decorators import login_required
from .filters import PostFilter
from django.db.models import Count
from .forms import CommentForm
from django.shortcuts import get_object_or_404, redirect
from django.db.models import Avg

# Create your views here.


from django.db.models import Count
def highest_rated_comment():
    highest_rated_comment = Comment.objects.annotate(avg_rating=Avg('ratings__rating')).order_by('-avg_rating')[:3]
    return highest_rated_comment
def post_list(request):
    top_comments = highest_rated_comment()
    post_list = Post.objects.annotate(comment_count=Count('comments'))
    myfilter = PostFilter(request.GET, queryset=post_list)
    post_list = myfilter.qs
    
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    context = {'posts': page_obj, 'top_comments': top_comments, 'myfilter': myfilter}
    return render(request, 'posts.html', context)




@login_required
def post_detail(request, slug):

    post = get_object_or_404(Post, slug=slug)
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.author = request.user
            comment.post = post
            # Check if the user is an advisor before saving
            if request.user.profile.account_type == 'advisor':
                comment.save()
                return redirect('mainpage:detail', slug=post.slug)
            else:
                # Handle cases where the user is not allowed to comment
                return HttpResponseForbidden("You are not authorized to comment.")
    else:
        comment_form = CommentForm()
    
    return render(request, 'post_detail.html', {'post': post, 'comment_form': comment_form})




def about(request):
    return render(request,'about.html')


def rate_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if request.method == 'POST' and request.user.profile.account_type == 'advisor':
        rating = request.POST.get('rating')
        CommentRating.objects.update_or_create(
            user=request.user,
            comment=comment,
            defaults={'rating': rating}
        )
        return redirect('mainpage:detail', slug=comment.post.slug)
    else:
        return HttpResponseForbidden("You are not authorized to rate comments.")
    

main_page/templates/about.html
{% extends "base.html" %}
{% load static %}
{% block body %}
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->


<!--================Blog Area =================-->
<section class="blog_area section-padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mb-5 mb-lg-0" dir="rtl">
                <div class="blog_left_sidebar">
                    <article class="blog_item">
                        <div class="blog_item_img">
                            <img src="{% static 'img/mooen.png' %}" width="100" height="95" alt="">
                          
                        </div>

                        <div class="blog_details">
                            <a class="d-inline-block" href="single-blog.html">
                                <h2>عن مُعين؟</h2>
                            </a>
                            <p>
                                مُعين هُنا لعينك في رحلتك الأكاديمية، يبصّرك بأهدافك، ويعينك على تحقيقها.
                                من خلال استشارات توجهك نحو النجاح الأكاديمي والمستقبل المهني المشرق.
                                </p>
                                <p>
                               <h4>لماذا مُعين؟</h4>
                                <p>
                                مستشارون متميزون:
                                يضم فريقًا من الخبراء المتخصصين في مجالات مختلفة. يمتلكون خبرة واسعة ويمكنهم توجيهك وتقديم النصائح المهمة.</p>
                                <p>
                                مجالات متنوعة:
                                يقدم استشارات في العديد من المجالات الأكاديمية المهمة. سواء كنت بحاجة لمساعدة في اختيار التخصص المناسب، أو تطوير مهارات الدراسة والبحث، أو التخطيط لمسار مهني في المجال الأكاديمي، فإننا هنا لمساعدتك.</p>
                                <p>
                                متابعة دائمة:
                                يمكنك حجز عدة جلسات لمتابعة استشارتك والاستفادة من المشورة المستمرة. نحن هنا لمساندتك ومساعدتك في جميع مراحل رحلتك الأكاديمية.</p>
                                <p>
                                مواعيد مرنة:
                                نحن ندرك أهمية جدولك الأكاديمي ونحن ملتزمون بتوفير مواعيد مرنة تتناسب مع احتياجاتك وجدولك.</p>
                           
                        </div>
                    </article>

                    

                  

                   

                   
                </div>
            </div>
           
        </div>
    </div>
</section>
{% endblock body %}

main_page/templates/post_detail.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}
{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3></h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    
                        
                        
                    <div class="card shadow-sm p-4 mb-4">
                        <!-- Combined image, title and description in a single card layout -->
                        <div class="d-flex justify-content-start align-items-start">
                            <div class="thumb mr-4">
                                {% if post.author.profile.photo %}
                                    <img src="{{post.author.profile.photo.url}}" alt="Job" width="82" height="82">
                                {% else %} 
                                    <img src="{% static 'img/user.png' %}" alt="Job" width="82" height="82">    
                                {% endif %}

                            </div>
                            <div class="jobs_content">
                                <h4>{{post.content}}</h4>
                                <p class="mb-0">{{post.title}}</p>
                            </div>
                        </div>
                    </div>


                    <div class="apply_job_form card shadow-sm p-4">
                        <h2> التعليقات :</h2>
                        {% for comment in post.comments.all %}
                            <div class="list-group-item list-group-item-action flex-column align-items-start">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-1">{{ comment.author }}</h5>
                                    <small>{{ comment.created_date }}</small>
                                </div>
                                <p class="mb-1">{{ comment.text }}</p>
                                <div>معدل التقييمات: {{ comment.ratings_average }} من 5</div> <!-- تأكد من استدعاء الدالة هنا -->
                                {% if user.is_authenticated and user.profile.account_type == 'advisor' %}
                                <form method="post" action="{% url 'mainpage:rate_comment' comment.id %}">
                                    {% csrf_token %}
                                    <input id="rating-input-{{ comment.id }}" name="rating" type="text" class="rating" data-size="xs">
                                    <button type="submit" class="boxed-btn3">أضف تققيم</button>
                                </form>
                                {% endif %}
                            </div>
                                
                        {% endfor %}
                       
                    </div>
                    <div class="apply_job_form white-bg">
                    {% if user.is_authenticated and user.profile.account_type == 'advisor' %}
                    <h4>أضف تعليقاً</h4>

                    <form method="post">
                        {% csrf_token %}
                        {{ comment_form.as_p }}
                        
                        <button class="boxed-btn3" type="submit">علّق</button>
                      
                    </form>
                    {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- footer start -->
  
{% endblock body %}

main_page/templates/posts.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}
{% block body %}
  

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{posts|length}} + عدد المنشورات</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <!-- job_listing_area_start  -->
    <div class="job_listing_area plus_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="job_filter white-bg">
                        <div class="form_inner white-bg">
                            <h3>البحث</h3>
                            <form method="GET">
                                {% bootstrap_form myfilter.form %}
                                
                                <input type="submit" value="بحث"  class="boxed-btn3 w-100 mt-3"  >
                            </form>
                        </div>

                    </div>
                </div>
                <div class="col-lg-9">
                

                    <div class="job_lists m-0">
                        <div class="row">
                            <div class="col-lg-12 col-md-12">
                                    <div class="single_jobs white-bg d-flex justify-content-between" style="border-radius: 53px; border: 5px #01293e solid;">
                                        {% for comment in top_comments %}

                                        <div class="jobs_left d-flex align-items-center">
                                            <div class="jobs_conetent">
                                                <a href="{% url 'mainpage:detail' comment.post.slug %}"><h4>أعلى النصائح تقييماً:</h4></a>
                                                <div class="links_locat d-flex align-items-center">
                                                    <div class="location">
                                                        <p>متوسط التقييم: {{ comment.avg_rating }} من 5</p>
                                                        <p>التعليق: {{ comment.text }}</p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="jobs_right">
                                            <div class="apply_now">
                                                <a href="{% url 'mainpage:detail' comment.post.slug %}" class="boxed-btn3">أنتقل للنصيحة</a>
                                            </div>
                                        </div>
                                        {% endfor %}

                                    </div>
                                                            </div>
                            {% for post in posts %}
                              
                            
                            <div class="col-lg-12 col-md-12">
                                <div class="single_jobs white-bg d-flex justify-content-between">
                                    <div class="jobs_left d-flex align-items-center">
                                        <div class="thumb">
                                            {% if post.author.profile.photo %}
                                                <img src="{{post.author.profile.photo.url}}" alt="Job" width="82" height="82">
                                            {% else %} 
                                                <img src="{% static 'img/user.png' %}" alt="Job" width="82" height="82">    
                                            {% endif %}
                                               
                                        </div>
                                        <div class="jobs_conetent">
                                            <a href="{% url 'mainpage:detail' post.slug %}"><h4>{{post.title}}</h4></a>
                                            <div class="links_locat d-flex align-items-center">
                                                <div class="location">
                                                    <p>{{post.content}}</p>
                                                    <p>عدد التعليقات: {{ post.comment_count }}</p>
                                                </div>
                                                {% comment %} <div class="location">
                                                    <p> <i class="fa fa-clock-o"></i>{{job.job_type}}</p>
                                                    {% url 'jobs:job_detail' job.slug %}
                                                </div> {% endcomment %}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="jobs_right">
                                        <div class="apply_now">
                                        </div>
                                        
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                           
                        </div>
                        {% if posts.has_other_pages  %}
                          
                        
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="pagination_wrap">
                                        <ul>
                                            {% if posts.has_previous %}                        
                                                <li><a href="?page={{posts.previous.page_number}}"> <i class="ti-angle-left"></i> </a></li>
                                            {% endif %}
                                            {% for i in posts.paginator.page_range %}                                           
                                                <li><a href="?page={{i}}"><span>{{i}}</span></a></li> 
                                            {% endfor %}
                                            {% if  posts.has_next %}
                                                <li><a href="?page={{posts.next.page_number}}"> <i class="ti-angle-right"></i> </a></li>
                                            {% endif %} 

                                        </ul>
                                    </div>
                                </div>
                            </div>
                         {% endif %} 
                     </div>
                </div>
            </div>
        </div>
    </div>
    <!-- job_listing_area_end  -->

    <!-- footer start -->
{% endblock body %}