Advisor/urls.py
from django.urls import path
from . import views
from .views import *
app_name = 'Advisor'
urlpatterns = [
    path('dashboard/', advisor_dashboard, name='advisor_dashboard'),
    path('manage-times/', manage_available_times, name='manage_available_times'),
    path('book-appointment/<int:advisor_id>/', book_appointment, name='book_appointment'),
    path('list-advisors/', list_advisors, name='list_advisors'),
    path('send-message/<int:appointment_id>/', send_message_view, name='send_message'),
    path('chat/<int:appointment_id>/', chat_page, name='chat_page'),
    path('chat_user/<int:appointment_id>/', user_chat_page, name='user_chat_page'),
]

dash_board/urls.py
from django.urls import path
from . import views
from .views import *
app_name = 'dash_board'
urlpatterns = [
    
    path('creat_post/',views.creat_post, name='creat_post'),
    
    
]

main_page/urls.py
from django.urls import path
from . import views
from .views import *
app_name = 'main_page'
urlpatterns = [


    path('',views.post_list, name='list'),
    path('<int:slug>',views.post_detail, name='detail'),
    path('about/',views.about,name='about'),
    path('rate_comment/<int:comment_id>/', rate_comment, name='rate_comment'),

]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('Accounts.urls',namespace='accounts')),
    path('', include('main_page.urls',namespace='mainpage')),
    path('dashboard/', include('dash_board.urls',namespace='dashboard')),
    path('advisor/', include('Advisor.urls',namespace='advisor')),
    
    
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.ALLOWED_HOSTS:
   
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}

<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Post Board</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="img/favicon.png">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/gijgo.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/slicknav.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-star-rating/css/star-rating.min.css" media="all" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;700&display=swap" rel="stylesheet" />


    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- <link rel="stylesheet" href="{% static 'css/responsive.css' %}"> -->
    <style>
        .rating-stars ul {
            list-style-type: none;
            padding: 0;
            display: inline-flex;
        }
        .rating-stars ul li {
            padding: 5px;
            color: #ffd700; /* لون ذهبي */
        }
    </style>
    
        
</head>

<body>
    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

    <!-- header-start -->
    <header style="font-family: 'Cairo', sans-serif;">
        <div class="header-area ">
            <div id="sticky-header" class="main-header-area">
                <div class="container-fluid ">
                    <div class="header_bottom_border">
                        <div class="row align-items-center">
                            <div class="col-xl-3 col-lg-2">
                                <div class="logo">
                                    <a href="">
                                        <img src="{% static 'img/mooen.png' %}" width="100" height="95" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-xl-6 col-lg-7">
                                <div class="main-menu  d-none d-lg-block">
                                    <nav>
                                        <ul id="navigation">
                                            <li><a href="{% url 'mainpage:list' %}">الرأيسية</a></li>
                                            <li><a href="{%url 'advisor:list_advisors'%}">المستشارين</a></li>
                                            <li><a href="{% url 'mainpage:about' %}">عن معين</a></li>
                                            
                                        </ul> 
                                    </nav>
                                </div>
                            </div>
                            <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                                <div class="Appointment">
                                    {% if request.user.is_authenticated %}
                                        <div class="phone_num d-none d-xl-block">
                                            <a href="{% url 'logout' %}">تسجيل الخروج</a>
                                        </div>
                                        {% if request.user.profile.account_type == 'advisor' %}
                                            <div class="phone_num d-none d-xl-block">
                                                <a class="boxed-btn3" href="{% url 'advisor:advisor_dashboard' %}"> صفحتي</a>
                                            </div>
                                        {% else %}
                                            <div class="phone_num d-none d-xl-block">
                                                <a class="boxed-btn3" href="{% url 'dashboard:creat_post' %}"> صفحتي</a>
                                            </div>
                                        
                                        {% endif %}
                                    {% else %}
                                        <div class="phone_num d-none d-xl-block">
                                            <a class = "boxed-btn3" href="{% url 'login' %}">تسجيل الدخول</a>
                                        </div>
                                    {% endif %}

                                    
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="mobile_menu d-block d-lg-none"></div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </header>
    <!-- header-end -->
    {% block body %}
      
    {% endblock body %}

    <!-- footer start -->
    <footer class="footer">
        <p>© all rights reserved 2023</p>
        </footer>
    <!--/ footer end  -->

    <!-- link that opens popup -->
    <!-- JS here -->
    
    <script src="{%static 'js/vendor/modernizr-3.5.0.min.js' %}"></script>
    <script src="{%static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{%static 'js/popper.min.js' %}"></script>
    <script src="{%static 'js/bootstrap.min.js' %}"></script>
    <script src="{%static 'js/owl.carousel.min.js' %}"></script>
    <script src="{%static 'js/isotope.pkgd.min.js' %}"></script>
    <script src="{%static 'js/ajax-form.js' %}"></script>
    <script src="{%static 'js/waypoints.min.js' %}"></script>
    <script src="{%static 'js/jquery.counterup.min.js' %}"></script>
    <script src="{%static 'js/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{%static 'js/scrollIt.js' %}"></script>
    <script src="{%static 'js/jquery.scrollUp.min.js' %}"></script>
    <script src="{%static 'js/wow.min.js' %}"></script>
    <script src="{%static 'js/nice-select.min.js' %}"></script>
    <script src="{%static 'js/jquery.slicknav.min.js' %}"></script>
    <script src="{%static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{%static 'js/plugins.js' %}"></script>
    <!-- <script src="{%static 'js/gijgo.min.js' %}"></script> -->
    <script src="{%static 'js/range.js' %}"></script>



    <!--contact js-->
    <script src="{%static 'js/contact.js' %}"></script>
    <script src="{%static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{%static 'js/jquery.form.js' %}"></script>
    <script src="{%static 'js/jquery.validate.min.js' %}"></script>
    <script src="{%static 'js/mail-script.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-star-rating/js/star-rating.min.js"></script>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{%static 'js/main.js' %}"></script>


	<script>
        $( function() {
            $( "#slider-range" ).slider({
                range: true,
                min: 0,
                max: 24600,
                values: [ 750, 24600 ],
                slide: function( event, ui ) {
                    $( "#amount" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] +"/ Year" );
                }
            });
            $( "#amount" ).val( "$" + $( "#slider-range" ).slider( "values", 0 ) +
                " - $" + $( "#slider-range" ).slider( "values", 1 ) + "/ Year");
        } );
        
        $(document).ready(function() {
            $('.rating-stars ul').each(function() {
                var $starsList = $(this);
                var ratingsAverage = parseFloat($starsList.attr('data-rating-average')); // تأكد من وضع هذه البيانات في HTML
                var starTotal = 5;
        
                $starsList.empty(); // تفريغ القائمة قبل إعادة ملء النجوم
        
                for (let i = 1; i <= starTotal; i++) {
                    // استخدام الفئات الصحيحة لنجوم FontAwesome
                    var starClass = i <= ratingsAverage ? 'fa fa-star' : 'fa fa-star-o';
                    $starsList.append($('<li class="star"><i class="' + starClass + '" aria-hidden="true"></i></li>'));
                }
            });
        });
           
            
        </script>
        
        
        
</body>

</html>

templates/base_generic.html
{% extends "base.html" %}

{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <div class="apply_job_form white-bg">
                        {% block content %}
                          
                        {% endblock content %}


                    </div>
                </div>

            </div>
        </div>
    </div>

    <!-- footer start -->
  
{% endblock body %}